### ISSUE TITLE
Add srclib slack to readme & set up auto invite page

### ISSUE THREAD

**Issue by samertm** [sourcegraph/srclib#114]

**Comment by charlesvickery** [comment]
+1

**Comment by jelmerdereus** [comment]
docs/overview.md in branch 'docsoverview' is extended with Slack info

**Comment by jelmerdereus** [comment]
@samertm please have a look at my commit of README

**Comment by beyang** [comment]
@jelmerdereus that looks great; feel free to go ahead and merge

**Comment by jelmerdereus** [comment]
@beyang this is committed to branch `docsoverview` just like the additions I made to docs/sources/overview.md . Could you have a look at it before I merge? thanks!
