### ISSUE TITLE
make: godep: No such file or directory

### ISSUE THREAD

**Issue by acgourley** [sourcegraph/srclib#119]
Alexs-MacBook-Air:Downloads acgourley$ src toolchain install-std
Installing/upgrading standard toolchains...

Go (sourcegraph.com/sourcegraph/srclib-go) ====================================
Symlinked toolchain sourcegraph.com/sourcegraph/srclib-go into your GOPATH at%!(EXTRA string=/Users/acgourley/gocode/src/sourcegraph.com/sourcegraph/srclib-go)
Downloading or updating Go toolchain in /Users/acgourley/.srclib/sourcegraph.com/sourcegraph/srclib-go
Running  [src toolchain get -u sourcegraph.com/sourcegraph/srclib-go]
Building Go toolchain program
Running  [make -C /Users/acgourley/.srclib/sourcegraph.com/sourcegraph/srclib-go]
go get github.com/tools/godep
godep go build -o .bin/srclib-go
make: godep: No such file or directory
make: *** [install] Error 1
failed to install/upgrade Go (sourcegraph.com/sourcegraph/srclib-go) toolchain: command ["make" "-C" "/Users/acgourley/.srclib/sourcegraph.com/sourcegraph/srclib-go"] failed: exit status 2

**Comment by acgourley** [comment]
resolution was to install godep AND add it to $PATH

**Comment by jxieeducation** [comment]
:) thx. had the exact error
