### ISSUE TITLE
Update Srcfile Docs

### ISSUE THREAD

**Issue by rameshvarun** [sourcegraph/srclib#13]
A TODO in [docs/sources/building/srcfile.md](https://github.com/sourcegraph/srclib/blob/master/docs/sources/building/srcfile.md) suggests that the Srcfile format has changed since the doc was written.

**Comment by shurcooL** [comment]
The [docs/sources/building/](https://github.com/sourcegraph/srclib/tree/master/docs/sources/building) folder no longer contains a `srclib.md` file. It was removed in 0ee8cf7ff55c754594fb3717e830251c578710cd. So that link is 404. 

Can this issue be closed then?

**Comment by beyang** [comment]
Yes, it can be closed. Thanks.
