### ISSUE TITLE
sourcegraph mode for the default CLI emacs under OS X doesn't work

### ISSUE THREAD

**Issue by mxi1** [sourcegraph/srclib#134]
The json-mode is required by sourcegraph-mode. 

However, the default CLI emacs app in OS X doesn't enable json-mode. So there will be always one error message to load the .emacs file.

I think the configuration mentioned in [Emacs Plugin](https://srclib.org/plugins/emacs/) should tell the users don't use the default CLI emacs under OS X.

**Comment by jelmerdereus** [comment]
I 'll change it

**Comment by jelmerdereus** [comment]
How do you like this?

**Comment by samertm** [comment]
Yes, thank you @jelmerdereus !
