### ISSUE TITLE
Go toolchain installation is skipped though "Go" language is installed

### ISSUE THREAD

**Issue by SlNPacifist** [sourcegraph/srclib#139]
I installed "Go" using ppa from launchpad (OS is Ubuntu 14.04), so I have "Go" in my system, but GOPATH is not set:
```
slnpacifist@slnpacifist-TWH:~/atom_workspace/test1$ go version
go version go1.4.1 linux/amd64
slnpacifist@slnpacifist-TWH:~/atom_workspace/test1$ echo $GOPATH

```
Thus, when I try to install toolchain for "Go", it just won't install:
```
slnpacifist@slnpacifist-TWH:~/atom_workspace/test1$ src toolchain install go
2015/04/26 10:44:31 Failed to detect git/hg repository root dir for "."; continuing.
Go (sourcegraph.com/sourcegraph/srclib-go) ====================================
skipped sourcegraph.com/sourcegraph/srclib-go: no GOPATH set (assuming Go is not installed and you don't want the Go toolchain)
The following toolchains were not installed:
Go (sourcegraph.com/sourcegraph/srclib-go)
````
And I couldn't find a way to force that toolchain installation

**Comment by sqs** [comment]
Try setting GOPATH=$HOME

**Comment by SlNPacifist** [comment]
Toolchain installation failed: https://gist.github.com/SlNPacifist/e5970bb3a21567c958c9

**Comment by shurcooL** [comment]
The build error was:

```
./config.go:163: loaderConfig.ImportFromBinary undefined (type loader.Config has no field or method ImportFromBinary)
./graph.go:387: loaderConfig.ImportFromBinary undefined (type loader.Config has no field or method ImportFromBinary)
```

It seems for some reason the latest version of `golang.org/x/tools/go/loader` is being used, despite the fact that an older version is vendored via godep and should be used instead. The latest version of `go/loader` no longer has `ImportFromBinary` as of https://github.com/golang/tools/commit/9c57c19a58835b00c0e3e283952087842242e49b. It seems godep is not doing its job for some reason.

**Comment by samertm** [comment]
should be fixed by this: https://github.com/sourcegraph/srclib-go/commit/b265227d842162c4d6c3abbed4d0dc1985311a94

**Comment by SlNPacifist** [comment]
Tried to install master branch of srclib-go according to https://github.com/sourcegraph/srclib-go#installation, but got error:
```
slnpacifist@slnpacifist-TWH:~/srclib-tmp$ go get -v sourcegraph.com/sourcegraph/srclib-go
(lots of downloads here)
src/sourcegraph.com/sourcegraph/srclib-go/config.go:163: loaderConfig.ImportFromBinary undefined (type loader.Config has no field or method ImportFromBinary)
src/sourcegraph.com/sourcegraph/srclib-go/graph.go:387: loaderConfig.ImportFromBinary undefined (type loader.Config has no field or method ImportFromBinary)
```

Full log available at https://gist.github.com/SlNPacifist/d408a53ee56c32b4dbd2
