### ISSUE TITLE
`src toolchain install go` fails

### ISSUE THREAD

**Issue by neelance** [sourcegraph/srclib#142]
I did

```
go get -u -v sourcegraph.com/sourcegraph/srclib/cmd/src
src toolchain install go
```

and got `depresolve.go:13:2: cannot find package "github.com/MarkMcCaskey/gddo/gosrc"`. Installing the missing package manually fixed it.

**Comment by jelmerdereus** [comment]
I think it should move to `srclib-go` since depresolve.go is not in this repo

**Comment by neelance** [comment]
Right. I've created https://github.com/sourcegraph/srclib-go/issues/33 instead. Closing.

**Comment by jelmerdereus** [comment]
Great, thanks @neelance :+1:
