### ISSUE TITLE
Cryptic error message in `toolchain.Lookup` function.

### ISSUE THREAD

**Issue by MaikuMori** [sourcegraph/srclib#157]
Is there a reason why this returns `os.ErrNotFound` when no toolchain is found instead of error with better message?

```go
// Lookup finds a toolchain by path in the SRCLIBPATH. For each DIR in
// SRCLIBPATH, it checks for the existence of DIR/PATH/Srclibtoolchain.
func Lookup(path string) (*Info, error) {
	if noToolchains {
		return nil, nil
	}

	path = filepath.Clean(path)

	matches, err := lookInPaths(filepath.Join(path, ConfigFilename), srclib.Path)
	if err != nil {
		return nil, err
	}

	if len(matches) == 0 {
		return nil, os.ErrNotExist
	}
	if len(matches) > 1 {
		return nil, fmt.Errorf("shadowed toolchain path %q (toolchains: %v)", path, matches)
	}
	return newInfo(path, filepath.Dir(matches[0]), ConfigFilename)
}
```
-- [source](https://github.com/sourcegraph/srclib/blob/master/toolchain/find.go#L14..L35)

Basically this was failing and the output I got from `src tool -m docker "sourcegraph.com/sourcegraph/srclib-python" "graph"` was:
```
file does not exist
exit status 1
```

**Comment by sqs** [comment]
No good reason I can think of. When this is changed, we will also need to update callers of this function that use `os.IsNotExist` to check the error category.
