### ISSUE TITLE
Schema needs description of build targets

### ISSUE THREAD

**Issue by xizhao** [sourcegraph/srclib#197]
Different build targets will have different information for depresolve, and what's included.

simple example is npm's dependencies vs devdependencies

Most of the time, only the most commonly consumed build target is what actually matters to the user, not a comprehensive stack of what's brought in during development, testing, etc...

How do we describe these in the schema?  Should we define multiple build targets as multiple source units, or have srcunits become an array to wrap build targets that then contain file, depresolve info, and etc...

**Comment by beyang** [comment]
Only dependencies that are true dependencies at the source code level (i.e., need to be present to build or run the code) should be listed as dependencies. Other dependencies can be listed in the `Data` field or some other field that offers additional information. Would this work for your use case?

It does not seem worthwhile to include them in the main dependency field and adding an additional source unit adds more complexity.

**Comment by xizhao** [comment]
Yup, mirrored the issue in srclib-js
https://github.com/sourcegraph/srclib-javascript/issues/17
