### ISSUE TITLE
slackin.srclib.org down?

### ISSUE THREAD

**Issue by jsyeo** [sourcegraph/srclib#218]
I am trying to get a slack invite but I can't seem to get slackin.srclib.org to load. :confounded:

**Comment by shurcooL** [comment]
I've noticed that too. @sqs, do you know how we can resolve that?

**Comment by beyang** [comment]
hey @jsyeo, sorry about the annoyance. The slackin should be back up later tonight, but in the meantime, I've sent an invite to your email.
