### ISSUE TITLE
Homebrew is outdated

### ISSUE THREAD

**Issue by thedrow** [sourcegraph/srclib#269]
Homebrew provides srclib 0.0.42 which sounds pretty old given that the repo is tagged with 0.2.5.

**Comment by beyang** [comment]
Sorry about that! srclib is under active development so we haven't shipped a stable release in awhile. If you want to try out the development version, you can just run `go get sourcegraph.com/sourcegraph/srclib/cmd/srclib` (you'll need to install Go 1.6 first).
