### ISSUE TITLE
unable to install go toolchain

### ISSUE THREAD

**Issue by LeanderK** [sourcegraph/srclib#300]
#### this is my output for running `src toolchain install go`: 
```
2016/06/15 21:28:59 Failed to detect git/hg repository root dir for "."; continuing.
Go (sourcegraph.com/sourcegraph/srclib-go) ====================================
mkdir -p /Users/LeanderK/go/src/sourcegraph.com/sourcegraph
ln -s /Users/LeanderK/.srclib/sourcegraph.com/sourcegraph/srclib-go /Users/LeanderK/go/src/sourcegraph.com/sourcegraph/srclib-go
Symlinked toolchain sourcegraph.com/sourcegraph/srclib-go into your GOPATH at /Users/LeanderK/go/src/sourcegraph.com/sourcegraph/srclib-go
Downloading or updating Go toolchain in /Users/LeanderK/.srclib/sourcegraph.com/sourcegraph/srclib-go
Running  [src toolchain get -u sourcegraph.com/sourcegraph/srclib-go]
2016/06/15 21:28:59 Failed to detect git/hg repository root dir for "."; continuing.
Cloning into '/Users/LeanderK/.srclib/sourcegraph.com/sourcegraph/srclib-go'...
remote: Counting objects: 6039, done.
remote: Total 6039 (delta 0), reused 0 (delta 0), pack-reused 6039
Receiving objects: 100% (6039/6039), 2.93 MiB | 1.73 MiB/s, done.
Resolving deltas: 100% (2300/2300), done.
Checking connectivity... done.
Building Go toolchain program
Running  [make -C /Users/LeanderK/.srclib/sourcegraph.com/sourcegraph/srclib-go]
go get github.com/kardianos/govendor
govendor sync
Error: Package "/Users/LeanderK/.srclib/sourcegraph.com/sourcegraph/srclib-go" not a go package or not in GOPATH.
govendor sync
	Ensures the contents of the vendor folder matches the vendor file.
	Options:
		-insecure    allow downloading over insecure connection
make: *** [govendor] Error 2
failed to install/upgrade Go (sourcegraph.com/sourcegraph/srclib-go) toolchain: skipped : 
The following toolchains were not installed:
Go (sourcegraph.com/sourcegraph/srclib-go)
```

#### running `src toolchain list` produces:
`2016/06/15 21:33:53 Failed to detect git/hg repository root dir for "."; continuing.
PATH                                      TYPE
sourcegraph.com/sourcegraph/srclib-go     
`
#### some further details:
- i am using srclib 0.0.42
- i installed it via home-brew (running it under OSX) and first called `src self update`
- `srclib` does not work, but `src`

**Comment by LeanderK** [comment]
also `src toolchain install java` gives me 
```
2016/06/15 21:28:53 Failed to detect git/hg repository root dir for "."; continuing.
Language java unrecognized. Standard languages include: go, python, ruby, javascript
```
while the repo clearly states otherwise. (`or you may run srclib toolchain install java which will clone the latest version to $SRCLIBPATH/sourcegraph.com/sourcegraph/srclib-java and build it.`). But this may be a documentation issue.

**Comment by alexsaveliev** [comment]
Hi,

I suggest you to switch to newer version of `src` - `srclib`. You can grab and build it using 
```sh
go get sourcegraph.com/sourcegraph/srclib
cd $GOPATH/src/sourcegraph.com/sourcegraph/srclib
make
```

recent versions of `srclib-go` and `srclib-java` toolchains (installed by `src toolchain install go`) are not compatible with the old `src` binary

> Language java unrecognized...

Documentation issue indeed, recent `srclib` provides `java` language support

> srclib does not work, but src

Could you please provide more details? We can discuss your issues on Slack, http://slackin.srclib.org/ if you want

**Comment by LeanderK** [comment]
solved my problems, thank you!
