### ISSUE TITLE
installed in sublime text 3, after installing src - nothing 

### ISSUE THREAD

**Issue by BobWalsh** [sourcegraph/srclib#64]
in SB3 build 3065, installed via package control Sourcegraph. Restarted ST3. This after installing src successfully. See the two commands in the popup menu - but nothing happens.

**Comment by alexandre-normand** [comment]
I'm having a related issue trying the sourcegraph integration in Sublime Text 3. I installed srcgraph using `go get` so `src` was on my path. `Sublime Text` didn't initially find it on my path (even though it is on my command-line path) but I then installed the [Fix Mac Path](https://github.com/int3h/SublimeFixMacPath) package to help with this.

Now the error I'm getting is the following:
```
Error message: Command '['src', 'api', 'describe', '--file', '/Users/alexandre.normand/projects/gowork/src/github.com/alexandre-normand/everytimisawesome/Godeps/_workspace/src/github.com/danryan/hal/config.go', '--start-byte', '1017', '--no-examples']' returned non-zero exit status 1
b''
b'2015/04/02 09:27:35 GOPATH must be set.\nlstat /Users/alexandre.normand/projects/gowork/src/github.com/alexandre-normand/everytimisawesome/.srclib-cache/3d942cee6b6bc92b9fc76fa81d297f18edfea2d9: no such file or directory\nfailed to scan for source units: scanner [/Users/alexandre.normand/.srclib/sourcegraph.com/sourcegraph/srclib-go/.bin/srclib-go scan]: EOF\n'
``` 

There's a mention of `GOPATH must be set` but it looks like it might be a red herring. `GOPATH` is correctly set as far as I can tell.
