### ISSUE TITLE
Differentiate between types of refs

### ISSUE THREAD

**Issue by sqs** [sourcegraph/srclib#77]
It'd be useful to differentiate between various kinds of refs: refs in imports, refs in type signatures, refs in definitions of things, and refs in code bodies, etc. That's because it's often not useful to see package imports when you want to see how a package is actually used, as in the following example:

![image](https://cloud.githubusercontent.com/assets/1976/5234848/aa451de6-77a4-11e4-814b-6e3259044290.png)
(from https://sourcegraph.com/hg.python.org/cpython@default/.PipPackage/Python/.def/_collections/defaultdict)

There's already a `Def bool` field on Ref, but perhaps it could be generalized to `Type enum` that can take values such as `def`, `dep` (import), `type`, etc.

(See also: http://www.mkdown.com/5f7fb62bdaf535ea9f00 by @Wilfred.)

**Comment by beyang** [comment]
This enhancement will go hand-in-hand with a broader rethinking of the srclib schema to handle richer def-ref relationships, so closing this.
